- name: Set Up Lock Screen
  become: true
  become_user: "{{ username }}"
  command: "{{ item }}"
  with_items:
    - "defaults -currentHost write com.apple.screensaver idleTime 0"
    - "defaults write com.apple.screensaver askForPassword -int 1"
    - "defaults write com.apple.screensaver askForPasswordDelay -int 0"
    - "defaults write com.apple.VoiceOver OnScreenUIEnabled -bool false"
    - "defaults write com.apple.universalaccess stickyKey -bool false"
    - "defaults write com.apple.universalaccess slowKey -bool false"
